name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build Sass
        run: npm run build:sass
      - name: Run CSS analysis
        run: npm run analyze-css
      - name: List produced CSS files
        run: ls -la css || true
